apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-service
  template:
    metadata:
      labels:
        app: sentiment-service
    spec:
      containers:
        - name: sentiment-service
          image: sentiment-service-image:latest
          ports:
            - containerPort: 5000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: openai
